services:
  postgres:
    container_name: interactify_postgres
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  interactify:
    container_name: interactify
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - '$PORT:$PORT'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev

volumes:
  redis-data:
  pgdata:

networks:
  app-network:
    driver: bridge
